// Emits the design tokens straight from the canvas source, so the app and the
// artboards cannot drift. Re-run after any palette change on the canvas:
//   node scripts/gen-tokens.mjs
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { LIGHT, DARK, CAT, SERIES, setTheme } from '../../design-v2/_build/lib.mjs';

const kebab = (k) => k.replace(/[A-Z]/g, (m) => '-' + m.toLowerCase());
const block = (t) => Object.entries(t).map(([k, v]) => `    --c-${kebab(k)}: ${v};`).join('\n');

setTheme('light');
const catL = { ...CAT }, seriesL = [...SERIES];
setTheme('dark');
const catD = { ...CAT }, seriesD = [...SERIES];
setTheme('light');

const cat = (c) => Object.entries(c)
  .map(([k, [tint, ink]]) => `    --cat-${k}: ${tint};\n    --cat-${k}-ink: ${ink};`).join('\n');
const series = (s) => s.map((v, i) => `    --series-${i + 1}: ${v};`).join('\n');

writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '../src/app/tokens.css'),
`/* GENERATED by scripts/gen-tokens.mjs — do not edit by hand.
   Source of truth is design-v2/_build/lib.mjs, which also builds the canvas. */
@layer base {
  :root {
${block(LIGHT)}
${cat(catL)}
${series(seriesL)}
    --font-ui: "Instrument Sans", ui-sans-serif, system-ui, -apple-system, sans-serif;
    --font-display: "Instrument Serif", Georgia, "Times New Roman", serif;
    --el: 0 1px 2px rgba(35,61,77,.05), 0 10px 26px -14px rgba(35,61,77,.20);
    --el2: 0 2px 8px rgba(35,61,77,.10), 0 22px 44px -20px rgba(35,61,77,.42);
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
${block(DARK)}
${cat(catD)}
${series(seriesD)}
      --el: 0 1px 2px rgba(0,0,0,.35), 0 10px 26px -14px rgba(0,0,0,.7);
      --el2: 0 2px 8px rgba(0,0,0,.4), 0 22px 44px -20px rgba(0,0,0,.85);
    }
  }

  :root[data-theme="dark"] {
${block(DARK)}
${cat(catD)}
${series(seriesD)}
    --el: 0 1px 2px rgba(0,0,0,.35), 0 10px 26px -14px rgba(0,0,0,.7);
    --el2: 0 2px 8px rgba(0,0,0,.4), 0 22px 44px -20px rgba(0,0,0,.85);
  }
}
`);
console.log('wrote src/app/tokens.css —', Object.keys(LIGHT).length, 'colour tokens,',
  Object.keys(catL).length, 'category tints,', seriesL.length, 'chart steps, both themes');
